### ISSUE TITLE
Giphy Agreement requires logo/attribution

### ISSUE THREAD

**Issue by OranguTech** [what-a-time-to-be-alive/what-a-time-to-be-alive#22]
https://developers.giphy.com/docs/

> As per our section 5 A of our terms of service, we require all apps that use the GIPHY API to conspicuously display "Powered By GIPHY" attribution marks where the API is utilized.

I'm submitting a pull request now. (Just adds a <p> definition to the CSS, one of the approved logos, and a footer.

**Comment by bryceosterhaus** [comment]
fixed by https://github.com/what-a-time-to-be-alive/what-a-time-to-be-alive/commit/6616b4be7f28ddfda3960f33eb17b4abf9cfd5e3

**Comment by OranguTech** [comment]
Interesting change. Don't know if it meets the intent of the provision, but it seems to match the spirit of this project. :)
